### ISSUE TITLE
Primary Issue: App Scaffolding

### ISSUE THREAD

**Issue by aerych** [Automattic/newspack-ios#12]
These are the anticipated high level tasks needed to lay the ground work for starting work on a v1.  

- [x] #1 Authentication
- [x] #2 App secrets
- [x] #3 Basic Networking/API layer
- [x] #4 Basic editor integration
- [x] #5 Stubbed media support
- [x] #6 Initial data model
- [x] #7 Stubbed post list
- [x] #9 Create a post
- [x] #10 Edit a post
- [x] #11 Browse and insert media into a post
