### ISSUE TITLE
Text Notes: Task list

### ISSUE THREAD

**Issue by aerych** [Automattic/newspack-ios#128]
Text Notes feature task list:

- [x] Display a simple text editor from the tool bar. 
- [x] Save new text notes and modify existing notes from the editor.  Save on close. Autosave on an interval.
- [x] Ensure notes are properly displayed in the assets list
- [ ] Bonus: Share text via the share extension.
