### ISSUE TITLE
V0 Lingering Issue Wrap up Punch List

### ISSUE THREAD

**Issue by aerych** [Automattic/newspack-ios#29]
A punch list of things to wrap up between v0 and v1 milestones:

- [x] https://github.com/Automattic/newspack-ios/issues/19 Ensure the view relies on actions when initiating work in stores. Media should be fine. Double check posts.
- [x] https://github.com/Automattic/newspack-ios/issues/27 Fix menu view controller presentation on iOS 13
- [x] https://github.com/Automattic/newspack-ios/issues/22 Double check we have good test coverage for posts
- [x] https://github.com/Automattic/newspack-ios/issues/17 Let's just remove the ghosts for now.
- [x] https://github.com/Automattic/newspack-ios/issues/16 Clean up trashed posts. Oguz had thoughts about this. 
- [ ] https://github.com/Automattic/newspack-ios/issues/20 and https://github.com/Automattic/newspack-ios/issues/21 Improve change detection in posts

For later exploration when there is time:

- [ ] https://github.com/Automattic/newspack-ios/issues/15 sync revisions with posts.
- [ ] https://github.com/Automattic/newspack-ios/issues/23 Implement post previews.
- [ ] Add scaffolding for syncing taxonomies like categories and tags.
