### ISSUE TITLE
Photos Milestone Task List

### ISSUE THREAD

**Issue by aerych** [Automattic/newspack-ios#91]
A list of tasks, grouped by category, for the Photos feature milestone.

### Core/System
- [x] Wire up media lib to photos and camera icons.  Photo icon should display device photo lib. Camera icon should open camera capture.  Selected/captured image should be processed to story folder.
- [x] Adjustments to core data layer for photo if needed. Existing models should do 90% of the job after v0.
- [x] Photo asset / file system reconciliation. Should already be 90% done after milestone 3.
- [x] Ensure folder manager is portable.

### UI Specific
- [x] Change sync icon to upload to cloud icon.
- [x] Custom cells for photo assets.
- [x] Replace video toolbar icon with camera icon.
- [x] Photo detail/edit screen, includes caption / meta data. Edit mode to modify.
- [x] Photo preview screen.
- [x] Maybe add pull to refresh to folders and assets lists.
- [x] Sync progress indicator in cell UI
- [x] Consolidate toolbar code between Story Folder and Assets screens.

### Network/Remote
- [x] Wire up draft post creation when story folder has assets.
- [x] If current story has a remote draft sync when current story is selected
- [x] Handle offline state. Defer network activity when there is no network. 
- [x] Attach and upload image when added.
- [x] Detect changes and sync modified image / meta data. Lasy sync property vs last modified property.
- [x] Clean up if post status is no longer draft. (TBD)

### Share Extension
- [x] Images can be shared to Newspack, defaulting to current story.
